compute_environment: LOCAL_MACHINE
distributed_type: 'NO'
deepspeed_config: {}
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 1
use_cpu: true